# Generated by Django 4.2.24 on 2026-05-25 12:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='featured_image',
        ),
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
